window.homepageConfig = {
  site: {
    title: "常志勇课题组",
    description: "东南大学 机械工程学院 仿生感知与智能装备团队",
  },

  // 图片路径支持 png、jpg、jpeg、webp、gif 等常见格式。
  // 更换素材时，把图片放进 assets 文件夹，然后把路径改成对应文件名即可。
  images: {
    heroBackground: "assets/background.jpg",
    logos: [
      { src: "assets/logo-1.png", alt: "东南大学 Logo" },
      { src: "assets/logo-2.png", alt: "东南大学机械工程学院 Logo" },
    ],
    sectionIcon: "assets/icon-flask.png",
  },

  group: {
    name: "常志勇课题组",
    organization: "东南大学 机械工程学院",
    team: "仿生感知与智能装备团队",
  },

  nav: [
    { label: "首页", href: "index.html" },
    { label: "学术科研", href: "academic.html" },
    { label: "研究成员", href: "members.html" },
    { label: "研究平台", href: "platform.html" },
    { label: "研究成果", href: "achievements.html" },
    { label: "学习生活", href: "life.html" },
    { label: "招生招聘", href: "recruit.html" },
  ],

  intro: {
    title: "课题组简介",
    moreLabel: "MORE>>",
    moreHref: "academic.html",
    bodyHtml:
      "本团队面向<strong class='mark-blue'>深海深地能源资源开发与智能装备</strong>的国家战略需求，发展<strong class='mark-blue'>深海油气仿生传感与随钻气测仪器</strong>关键技术；设计和构建<strong class='mark-blue'>钻探机器人、井下传感器与智能探测装备</strong>等特种装备系统；发展<strong class='mark-blue'>复杂环境多物理参量同步感知与精准控制技术</strong>，深刻揭示深海深地钻探过程中装备感知、载荷传递与多参数耦合响应机制，为深海油气开发、极地探测和特深井安全高效钻进提供技术支撑。",
    recruitHtml:
      "欢迎具备<strong class='mark-red'>机械、电子、自动化、仪器、控制、人工智能、海洋工程、石油工程</strong>等不同专业背景的学生报考<strong class='mark-red'>硕士、博士研究生</strong>或<strong class='mark-red'>博士后研究</strong>。",
  },

  joinHighlights: [
    {
      title: "真实工程场景",
      text: "围绕深海、深地、极地和油气开发需求开展研究，课题来自真实装备、真实现场和国家重大任务。",
      tags: ["深海深地", "极地探测", "工程装备"],
    },
    {
      title: "交叉学科成长",
      text: "机械、电子、仪器、控制、人工智能、海洋工程和石油工程背景都能找到切入点，适合愿意跨界做系统的学生。",
      tags: ["传感", "机器人", "AI 控制"],
    },
    {
      title: "论文专利与转化",
      text: "学生可参与论文发表、专利布局、样机研制和外场验证，研究成果既面向高水平发表，也面向产业应用。",
      tags: ["SCI", "专利", "成果转化"],
    },
    {
      title: "有挑战也有支撑",
      text: "课题难度高，但有项目平台、团队协作和导师指导支撑，适合想做硬核科研和工程攻关的同学。",
      tags: ["项目训练", "团队协作", "导师指导"],
    },
  ],

  researchCards: [
    {
      title: "水下传感芯片与仿生感知",
      image: "assets/academic-1.png",
      alt: "围绕水下传感芯片、嗅觉感知与多源信息融合，支撑深海油气水下特种作业机器人环境感知。",
      href: "academic.html#research-1",
      tags: ["传感芯片", "仿生感知"],
      studentTasks: ["传感结构设计", "水下实验数据采集", "多源感知算法验证"],
    },
    {
      title: "水下特种机器人创新设计与人机交互",
      image: "assets/academic-2.png",
      alt: "面向深海油气装备安装、巡检、维护与应急处置，开展水下特种机器人结构设计和人机交互研究。",
      href: "academic.html#research-2",
      tags: ["特种机器人", "人机交互"],
      studentTasks: ["机器人机构建模", "样机装调测试", "人机交互方案设计"],
    },
    {
      title: "水下机器人仿生控制与集群协同",
      image: "assets/academic-3.png",
      alt: "研究水下机器人仿生控制、AUV/ROV 协同、集群作业和复杂环境下的任务规划方法。",
      href: "academic.html#research-3",
      tags: ["仿生控制", "集群协同"],
      studentTasks: ["控制算法仿真", "协同任务规划", "AUV/ROV 实验验证"],
    },
    {
      title: "仿生嗅觉导航机器人",
      image: "assets/academic-4.png",
      alt: "融合多传感仿生感知、类脑嗅觉导航、脑机驱动人机增强和数字孪生，实现气味源追踪与智能作业。",
      href: "academic.html#research-4",
      tags: ["嗅觉导航", "数字孪生"],
      studentTasks: ["气味源追踪实验", "数字孪生场景搭建", "仿生导航策略开发"],
    },
    {
      title: "高精度气体特异传感阵列",
      image: "assets/academic-5.png",
      alt: "发展气敏电阻式传感芯片、阵列集成与选择性识别方法，提升复杂气体环境中的特异感知能力。",
      href: "academic.html#research-5",
      tags: ["气敏芯片", "传感阵列"],
      studentTasks: ["气敏材料测试", "传感阵列搭建", "特征识别模型训练"],
    },
    {
      title: "红外激光传感器与仿生电子鼻",
      image: "assets/academic-6.png",
      alt: "结合红外激光传感器、仿生电子鼻和多组分识别算法，构建高精度气体检测与识别系统。",
      href: "academic.html#research-6",
      tags: ["红外激光", "电子鼻"],
      studentTasks: ["光路与气路调试", "电子鼻采样实验", "多组分识别算法"],
    },
    {
      title: "复杂条件气体采样与灵敏探测",
      image: "assets/academic-7.png",
      alt: "面向深空、深海、深地、极地等复杂条件，开展气体采样、富集和低浓度多组分灵敏探测。",
      href: "academic.html#research-7",
      tags: ["极端环境", "灵敏探测"],
      studentTasks: ["采样装置设计", "低浓度检测实验", "极端环境适应性验证"],
    },
    {
      title: "低浓度随钻采样与座舱气相调控",
      image: "assets/academic-8.png",
      alt: "研究多组分低浓度随钻采样检测，以及高端汽车座舱、地外空间站等气相环境的仿生智能调控。",
      href: "academic.html#research-8",
      tags: ["随钻采样", "气相调控"],
      studentTasks: ["随钻气测系统开发", "座舱气相调控实验", "智能调控模型建立"],
    },
  ],

  updates: [
    { date: "2024-2027", text: "承担深地国家科技重大专项专题，面向特深井底钻压精准控制关键理论与技术。" },
    { date: "2023-2027", text: "承担国家重点研发计划“深海和极地关键技术与装备”专项课题。" },
    { date: "2023-2026", text: "承担国家自然科学基金联合重点项目，围绕高温高压高湿多相流体中微量硫化氢气液分离和敏感机理开展研究。" },
  ],

  reports: [
    {
      date: "2026",
      type: "报道",
      title: "新华网报道我国第42次南极科考新突破",
      href: "https://www.xinhuanet.com/government/20260409/b0e7ac4983ef4c7abbd574dd809d9fdb/c.html",
      text: "报道聚焦秦岭站业务化运行、冰盖热水钻探、国产极地装备应用、南大洋生态调查和航空保障等突破，呼应团队极地探测与复杂条件采样研究方向。",
    },
    {
      date: "2025",
      type: "报道",
      title: "人民日报报道长春推动科技成果向现实生产力转化",
      href: "assets/人民日报报道.png",
      text: "《人民日报》2025年8月9日第01版报道提及常志勇教授在长春试车场地测试脑机接口设备，系统延时小于 0.2 秒。",
    },
    {
      date: "2025",
      type: "报道",
      title: "光电行业门户报道光驱动下的智能净水机器人",
      href: "https://b2b.csoe.org.cn/news/show-807.html",
      text: "报道介绍吉林大学张永来教授团队联合常志勇教授团队在 PhotoniX 发表光驱动光催化蒸发器研究，构建无需电池、路径可控的智能净水机器人。",
    },
    {
      date: "2024",
      type: "报道",
      title: "吉林省科技厅报道气体仿生传感与随钻融合监控技术",
      href: "https://kjt.jl.gov.cn/xwzx/kjcg/202404/t20240410_8892470.html",
      text: "报道介绍团队建立气体仿生特异传感与随钻多相融合监控关键技术体系，该技术荣获 2023 年度吉林省科技进步奖一等奖。",
    },
    {
      date: "2024",
      type: "报道",
      title: "人民网报道“地壳一号”向地球深部进军",
      href: "http://jl.people.com.cn/n2/2024/0730/c349771-40928696.html",
      text: "报道聚焦吉林大学自主研发的“地壳一号”万米钻机及深部科学钻探，呈现地球深部探测与能源探测方向的吉林科技成果。",
    },
    {
      date: "2024",
      type: "获奖",
      title: "中国商业联合会技术发明奖一等奖",
      href: "https://me.seu.edu.cn/czy/list.htm",
      text: "常志勇教授获中国商业联合会技术发明奖一等奖，排名第 1。",
    },
    {
      date: "2023",
      type: "获奖",
      title: "吉林省科学技术进步奖一等奖",
      href: "https://kjt.jl.gov.cn/xwzx/kjcg/202404/t20240410_8892470.html",
      text: "常志勇教授获吉林省科学技术进步奖一等奖，排名第 1。",
    },
    {
      date: "应用",
      type: "转化",
      title: "相关技术在中国石油吉林油田、中国一汽等单位转化应用",
      href: "https://me.seu.edu.cn/czy/list.htm",
      text: "围绕气体仿生感知、智能检测与工程装备方向，支撑油田现场和产业场景应用。",
    },
    {
      date: "2025",
      type: "授权",
      title: "随钻原位南极冰层痕量气体富集监测装置获授权",
      href: "https://patents.google.com/patent/CN119309872B/zh",
      text: "发明专利 ZL202411457168.5，公告号 CN119309872B。",
    },
  ],

  pages: {
    academic: {
      title: "学术科研",
      kicker: "Research",
      summary:
        "团队围绕深海油气水下特种作业机器人、仿生嗅觉导航机器人、高精度气体特异传感阵列和复杂条件气体采样与灵敏探测开展研究，形成从传感芯片、机器人本体与控制，到气体采样检测和智能调控应用的研究链条。",
      coverImage: "assets/page-covers/page-academic.jpg",
      sections: [
        {
          title: "深海油气水下特种作业机器人",
          body:
            "面向深海油气设施安装、巡检、维护和应急处置，开展水下传感芯片、仿生感知、水下特种机器人创新设计、人机交互、仿生控制与集群协同研究。",
          bullets: ["水下传感芯片", "仿生感知", "特种机器人设计", "集群协同"],
        },
        {
          title: "仿生嗅觉导航机器人",
          body:
            "研究特种机器人多传感仿生融合导航、类脑嗅觉感知与导航、脑机驱动的人机增强和数字孪生技术，提升机器人在气味源搜索、风险识别和复杂环境作业中的自主性。",
          bullets: ["多传感仿生融合", "类脑嗅觉导航", "人机增强", "数字孪生"],
        },
        {
          title: "高精度气体特异传感阵列",
          body:
            "围绕气敏电阻式传感芯片、红外激光传感器和仿生电子鼻，开展高精度、特异性、阵列化气体感知与多组分识别研究。",
          bullets: ["气敏电阻芯片", "红外激光传感", "仿生电子鼻", "多组分识别"],
        },
        {
          title: "复杂条件气体采样与灵敏探测",
          body:
            "面向深空、深海、深地和极地等复杂条件，发展气体采样与灵敏探测、多组分低浓度随钻采样检测，以及高端汽车座舱和地外空间站气相环境的仿生智能调控。",
          bullets: ["深空/深海/深地/极地", "随钻气体采样", "低浓度多组分探测", "座舱气相调控"],
        },
      ],
    },

    members: {
      title: "研究成员",
      kicker: "People",
      summary:
        "展示院士顾问、课题组教师和博士后成员，呈现团队人才结构、个人主页和主要研究方向。",
      coverImage: "assets/page-covers/page-members.jpg",
      groups: [
        {
          title: "院士顾问",
          people: [
            {
              name: "孙友宏",
              role: "中国工程院院士 / 常志勇教授导师",
              image: "assets/member-1.png",
              href: "https://www.seu.edu.cn/2025/0224/c28449a519266/page.htm",
              desc: "东南大学校长、教授、博士生导师，中国工程院院士；长期致力于深地、深海、极地和国家潜在油气资源等领域研究。",
              tags: ["院士", "导师", "深地深海极地"],
            },
          ],
        },
        {
          title: "课题组教师",
          people: [
            {
              name: "常志勇",
              role: "教授 / 博士生导师",
              image: "assets/member-2.png",
              href: "https://me.seu.edu.cn/czy/list.htm",
              desc: "长期从事深海油气仿生传感与钻探机器人、随钻气测仪器与智能探测装备研究。",
              tags: ["课题组负责人", "深海深地", "钻探机器人"],
            },
            {
              name: "翁小辉",
              role: "教师",
              image: "assets/member-3.png",
              href: "https://me.seu.edu.cn/wxh/list.htm",
              desc: "东南大学机械工程学院教师，参与团队仿生传感、智能探测装备和工程实验方向研究。",
              tags: ["教师", "仿生传感", "智能探测"],
            },
            {
              name: "张涛",
              role: "教师",
              image: "assets/member-4.png",
              href: "https://ins.seu.edu.cn/zt/list.htm",
              desc: "参与导航控制、传感探测与跨学院协同研究，支撑团队多学科交叉方向建设。",
              tags: ["教师", "导航控制", "协同研究"],
            },
            {
              id: "xiadan",
              name: "夏丹",
              role: "教师",
              image: "assets/member-xiadan.png",
              href: "https://me.seu.edu.cn/xd/list.htm",
              desc: "课题组教师，参与深海油气水下机器人、仿生感知、气体传感与智能装备相关方向建设。",
              tags: ["教师", "仿生感知", "智能装备"],
            },
          ],
        },
        {
          title: "博士后",
          people: [
            {
              name: "靳宏杨",
              role: "博士后",
              image: "assets/member-5.png",
              href: "https://me.seu.edu.cn/jhy/list.htm",
              desc: "东南大学机械工程学院博士后，参与随钻气测、仿生感知、智能探测装备等方向研究。",
              tags: ["博士后", "随钻气测", "智能探测"],
            },
            {
              id: "zhaoshuai",
              name: "赵帅",
              role: "博士后",
              image: "assets/member-zhaoshuai.png",
              href: "profile.html?id=zhaoshuai",
              desc: "课题组博士后，参与水下特种机器人、仿生导航或复杂环境智能探测等方向研究。",
              tags: ["博士后", "水下机器人", "仿生导航"],
            },
            {
              id: "zhanglei",
              name: "张磊",
              role: "博士后",
              image: "assets/member-zhanglei.png",
              href: "profile.html?id=zhanglei",
              desc: "课题组博士后，参与气体采样检测、传感阵列或随钻气测装备相关研究。",
              tags: ["博士后", "气体检测", "传感阵列"],
            },
            {
              id: "kongcheng",
              name: "孔铖",
              role: "博士后",
              image: "assets/member-kongcheng.png",
              href: "profile.html?id=kongcheng",
              desc: "课题组博士后，参与复杂条件气体采样、智能探测装备和工程应用验证相关研究。",
              tags: ["博士后", "复杂环境", "工程验证"],
            },
          ],
        },
      ],
    },

    platform: {
      title: "研究平台",
      kicker: "Facilities",
      summary:
        "研究平台支撑水下特种机器人、气体传感阵列、随钻气体采样与复杂环境探测等方向的样机研制、标定测试和工程验证。",
      coverImage: "assets/page-covers/page-platform.jpg",
      items: [
        {
          title: "水下特种作业机器人平台",
          image: "assets/platform-1.png",
          href: "#platform-1",
          desc: "支撑水下机器人结构设计、仿生控制、人机交互和集群协同作业方法验证。",
          specs: ["水下仿生感知", "特种机器人", "集群协同"],
        },
        {
          title: "气体特异传感阵列平台",
          image: "assets/platform-2.png",
          href: "#platform-2",
          desc: "开展气敏电阻式传感芯片、红外激光传感器和仿生电子鼻的标定、阵列集成与多组分识别。",
          specs: ["气敏芯片", "红外激光", "仿生电子鼻"],
        },
        {
          title: "复杂条件气体采样与随钻探测平台",
          image: "assets/platform-3.png",
          href: "#platform-3",
          desc: "面向深空、深海、深地、极地等复杂条件开展气体采样、低浓度组分探测和随钻气测技术验证。",
          specs: ["随钻采样", "痕量气体", "复杂环境"],
        },
      ],
    },

    achievements: {
      title: "研究成果",
      kicker: "Achievements",
      summary:
        "汇集团队 82 条 SCI 论文、25 件发明专利和近三年代表性科研项目，论文链接指向 DOI 或期刊页面，专利链接指向公开专利详情页。",
      coverImage: "assets/page-covers/page-achievements.jpg",
      stats: [
        { value: "82", label: "SCI 论文", text: "覆盖气体传感、仿生电子鼻、随钻监测、智能装备等方向。" },
        { value: "25", label: "授权发明专利", text: "围绕随钻气测、仿生传感、复杂环境采样等关键技术布局。" },
        { value: "3+", label: "国家级/省部级项目", text: "支撑学生参与真实科研任务和工程系统开发。" },
        { value: "多项", label: "媒体报道与成果转化", text: "新华社、人民日报、科技厅等报道展现成果应用价值。" },
      ],
      groups: [
        {
          title: "代表性论文",
          type: "论文",
          records: [
            {
              year: "2026",
              title: "High-Adhesion Quadruple Hydrogen-Bonded Ionogels: A Dual-Function Platform for Gesture Recognition and Real-Time NH3 Detection in Multiscenario",
              href: "https://doi.org/10.1002/eem2.70189",
              desc: "Energy and Environmental Materials，2026, 9(3): e70189；影响因子：14.1；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Haohao Lin, Xiaotong Ma, Zihao Chen, Long Yang, Zitong Kan, Ruochen An, Lin Xu*, Zhiyong Chang*",
              tags: ["Energy and Environmental M...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "Application of electronic nose technology in wastewater treatment plants monitoring: Progress and future developments",
              href: "https://doi.org/10.1016/j.microc.2026.117768",
              desc: "Microchemical Journal，2026, 224: 117768；影响因子：5.1；中科院2区 / JCR Q1；通讯情况：通讯；作者：Bingyang Wang, Yu Yan, Ruochen An, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Microchemical Journal", "中科院2区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "Porous ceramics prepared by non-solvent-induced phase separation: progress, challenges, and prospects",
              href: "https://doi.org/10.1016/j.seppur.2025.136565",
              desc: "Separation and Purification Technology，2026,387: 136565；影响因子：9；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Wei Yang, Mi Wang, Xiaohui Weng, Guolong Lu*, Zhiyong Chang*, Youhong Sun",
              tags: ["Separation and Purificatio...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "Modulation of Ice Formation and Removal Dynamics by Antifreeze Protein-Inspired Large-Area Films",
              href: "https://doi.org/10.1002/adfm.202528042",
              desc: "Advanced Functional Materials，2026, 0: e28042；影响因子：19；中科院1区 / JCR Q1；通讯情况：三通讯；作者：Qiang Wang, Yue Yuan, Huanyu Zhao, Yi-Bo Zhao, Zhiyong Chang*, Yong-Lai Zhang*, Dong-Dong Han*",
              tags: ["Advanced Functional Materi...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "PDMS/porous ceramic membrane with dendritic directional pore structure for gas-liquid separation",
              href: "https://doi.org/10.1016/j.jece.2025.120866",
              desc: "Journal of Environmental Chemical Engineering，2026, 14(1): 120866；影响因子：7.2；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Wei Yang, Mi Wang, Xiaohui Weng, Guolong Lu*, Zhiyong Chang*, Youhong Sun",
              tags: ["Journal of Environmental C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "An electronic nose based on a humidity compensation mechanism for monitoring mine fires",
              href: "https://doi.org/10.1016/j.sna.2025.117115",
              desc: "Sensors and Actuators A: Physical，2025, 396: 117115；影响因子：4.9；中科院2区 / JCR Q1；通讯情况：双通讯；作者：Changjun Guan, Xiangrun Pan, Xiangyu Luan, Hang Sun, Xiaohui Weng*, Zhiyong Chang*",
              tags: ["Sensors and Actuators A: P...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Bioinspired mode-noise suppressed off-axis integrated cavity for rapid dynamic gas detection",
              href: "https://doi.org/10.1021/acssensors.5c01516",
              desc: "ACS Sensors，2025, 10: 9294-9305；影响因子：9.1；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Lei Zhang, Xietao Wang, Xiangyu Luan, Hongyang Jin, Zixun Geng, Yishen Zhou, Kaiyuan Zheng, Chuantao Zheng*, Zhiyong Chang*",
              tags: ["ACS Sensors", "中科院1区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "An electronic nose combined with qualitative-quantitative two-stage hybrid model for wastewater detection in wastewater treatment plants",
              href: "https://doi.org/10.1016/j.snb.2025.139115",
              desc: "Sensors and Actuators B: Chemical，2025,449: 139115；影响因子：7.7；中科院1区 / JCR Q1；通讯情况：通讯；作者：Bingyang Wang, Xiaodan Li, Donghui Chen, Ying Hu, Xiao Yang, Cheng Kong, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Artificial intelligence and microfluidics empower bionic sensing: Small sampling chambers assist in high sensitivity gas detection",
              href: "https://doi.org/10.1016/j.snb.2025.138542",
              desc: "Sensors and Actuators B: Chemical，2025, 445: 138542；影响因子：7.7；中科院1区 / JCR Q1；通讯情况：通讯；作者：Helin Wang, Zihao Chen, Xuezhi Chang, Tao Zhang, Zongwei Yao, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Sensing while drilling and intelligent monitoring technology: research progress and application prospects",
              href: "https://doi.org/10.3390/s25206368",
              desc: "Sensors，2025, 25(20): 6368；影响因子：3.5；中科院2区 / JCR Q2；通讯情况：双通讯；作者：Xiaoyu Liu, Zongwei Yao, Tao Zhang 4*, Zhiyong Chang*",
              tags: ["Sensors", "中科院2区", "JCR Q2"],
            },
            {
              year: "2025",
              title: "Deep learning framework for oil shale pyrolysis state recognition using bionic electronic nose",
              href: "https://doi.org/10.1007/s44196-025-00913-5",
              desc: "International Journal of Computational Intelligence Systems，2025, 18(1): 179；影响因子：3；中科院4区 / JCR Q2；通讯情况：双通讯；作者：Yuping Yuan, Xiaohui Weng, Yuheng Qiao, Xiaohu Shi*, Zhiyong Chang*",
              tags: ["International Journal of C...", "中科院4区", "JCR Q2"],
            },
            {
              year: "2025",
              title: "Bionic enriched olfactory system with preconcentration-enhanced sensing and hierarchical regression analysis strategy for ultra-sensitive detection of soil petroleum hydrocarbon contamination",
              href: "https://doi.org/10.1016/j.snb.2025.138424",
              desc: "Sensors and Actuators B: Chemical，2025, 444: 138424；影响因子：7.7；中科院1区 / JCR Q1；作者：Hongyang Jin, Zihao Chen, Shuai Zhao, Xiangyu Luan, Tao Zhang, Cheng Kong, Zongwei Yao*, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2026",
              title: "DAFF-SNN: Dual Attention-driven and Feature Fusion-based Spiking Neural Network for Epilepsy Detection based on Electroencephalogram",
              href: "https://doi.org/10.1109/jbhi.2025.3589392",
              desc: "IEEE journal of biomedical and health informatics，2026, 30(1): 315-327；影响因子：6.8；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Tao Zhang*, Lanqi He, Dingguo Zhang, Mingyang Li, Zhiyong Chang*",
              tags: ["IEEE journal of biomedical...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Bionic electronic nose system based on integrated dust augmentation idea for hierarchical early warning of mine fires",
              href: "https://doi.org/10.1016/j.snb.2025.138069",
              desc: "Sensors and Actuators B: Chemical，2025, 442: 138069；影响因子：7.7；中科院1区 / JCR Q1；通讯情况：通讯；作者：Xiangyu Luan, Hongyang Jin, Cheng Kong, Xiangrun Pan, Zihao Chen, Xiaotong Ma, Ruochen An, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Advancements in gas-liquid separation based on membrane contactors: Critical factors enhancing separation efficiency",
              href: "https://doi.org/10.1016/j.psep.2025.107350",
              desc: "Process Safety and Environmental Protection，2025, 200: 107350；影响因子：7.8；中科院1区 / JCR Q1；通讯情况：通讯；作者：Helin Wang, Tao Zhang, Ruochen An, Lin Sun, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Process Safety and Environ...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "A bio-inspired gas sensing sampling chamber inspired by the sensitive olfaction of sturgeons: Achieving low-power inspection and high-sensitivity sensing",
              href: "https://doi.org/10.1016/j.snb.2025.137536",
              desc: "Sensors and Actuators B: Chemical，2025, 433: 137536；影响因子：7.7；中科院1区 / JCR Q1；通讯情况：通讯；作者：Hongyang Jin, Xuezhi Chang, Xiangyu Luan, Zihao Chen, Tao Zhang, Jingmin Dang, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Light-propelled photocatalytic evaporator for robotic solar-driven water purification",
              href: "https://doi.org/10.1186/s43074-025-00169-4",
              desc: "PhotoniX，2025, 6: 11；影响因子：19.1；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Dongdong Han, Qiang Wang, Zhaodi Chen, Lei Wang, Zhiyong Chang*, Shengyi Xie, Xianbin Li, Wei Zhang, Yonglai Zhang*",
              tags: ["PhotoniX", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Dual biomimetic gas–liquid separation system with fluid steering function: synergistic enhancement to improve separation efficiency",
              href: "https://doi.org/10.1016/j.seppur.2025.133167",
              desc: "Separation and Purification Technology，2025, 371: 133167；影响因子：9；中科院1区 / JCR Q1；通讯情况：通讯；作者：Helin Wang, Xiaodan Li, Xiaotong Ma, Ruochen An, Tao Zhang, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Separation and Purificatio...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Efficient detection technology of Ganoderma lucidum spore powder quality based on electronic nose",
              href: "https://doi.org/10.1016/j.cej.2025.162158",
              desc: "Chemical Engineering Journal，2025, 511: 162158；影响因子：13.2；中科院1区 / JCR Q1；通讯情况：三通讯；作者：Jianlei Qiao, Jinying Li, Chang Liu, Yi Zhang, Shuang Liu*, Xiaohui Weng*, Zhiyong Chang*",
              tags: ["Chemical Engineering Journal", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Bioinspired sensor and actuator hybrid pixel array for moisture/temperature mapping, electrothermal display and programmable deformation",
              href: "https://doi.org/10.1021/acs.nanolett.5c00294",
              desc: "Nano Letters，2025, ﻿25: 4586-4595；影响因子：9.1；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Jiarui Zhang, Ang Li, Xilin Li, Zhiyong Chang*, Dongdong Han, Yonglai Zhang*",
              tags: ["Nano Letters", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Near-infrared mobile cloud OA-ICOS sensor system for atmospheric carbon dioxide monitoring",
              href: "https://doi.org/10.1021/acs.analchem.4c05644",
              desc: "Analytical Chemistry，2025, 97(7): 4021-4030；影响因子：6.7；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Lei Zhang, Ying Hua, Yishen Zhou, Kaiyuan Zheng, Fang Song, Zhiyong Chang*, Chuantao Zheng*",
              tags: ["Analytical Chemistry", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "Phosphine oxide functionalized porous aromatic frameworks enabled wireless bionic olfactory system with preconcentration capability for trace ammonia monitoring",
              href: "https://doi.org/10.1016/j.cej.2025.160282",
              desc: "Chemical Engineering Journal，2025, 506: 160282；影响因子：13.2；中科院1区 / JCR Q1；通讯情况：通讯；作者：Shuai Zhao, Hongyang Jin, Zihao Chen, Yonglai Zhang, Xiaoqin Zou, Lin Xu, Shaolei Wang, Zhenglei Yu, Zhiyong Chang*",
              tags: ["Chemical Engineering Journal", "中科院1区", "JCR Q1"],
            },
            {
              year: "2025",
              title: "An electronic nose combined with qualitative-quantitative two-stage hybrid modeling for microbial quantitative prediction in automotive air conditioners",
              href: "https://doi.org/10.1016/j.snb.2024.137083",
              desc: "Sensors and Actuators B: Chemical，2025, 427: 137083；影响因子：7.7；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Lidong Tan, Yonglong Ren, Tao Zhang, Cheng Kong, Xiaohui Weng*, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Preparation and regulation of high-strength and high-permeability porous ceramic/PDMS composite membranes for gas-liquid separation",
              href: "https://doi.org/10.1016/j.apsusc.2024.161114",
              desc: "Applied Surface Science，2024, 678: 161114；影响因子：6.9；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Wei Yang, Hao Cui, Mi Wang, Xiaohui Weng, Guolong Lu*, Zhiyong Chang*, Youhong Sun",
              tags: ["Applied Surface Science", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "A customized zeolitic imidazolate framework enabling bionic preconcentration of ultralow CO2",
              href: "https://doi.org/10.1007/s40843-024-3044-0",
              desc: "Science China-Materials，2024, 67(10): 3401-3407；影响因子：6.8；中科院1区 / JCR Q1；通讯情况：通讯；作者：Hongyang Jin, Ziyang Wang, Guangli Yu, Junchao Dong, Shuai Zhao, Fengchao Cui, Hao Zhang, Guolong Lu, Xiaoqin Zou, Zhiyong Chang*",
              tags: ["Science China-Materials", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "A multimodal sensing network based on synergistically sensitized polyaniline composites strategy for safety monitoring in pesticide spraying",
              href: "https://doi.org/10.1016/j.snb.2024.136486",
              desc: "Sensors and Actuators B: Chemical，2024, 420: 136486；影响因子：8；中科院1区 / JCR Q1；通讯情况：三通讯；作者：Long Yang, Haiyang Huang, Qingqing Zhou, Zitong Kan, Yu Qi, Biao Dong, Hongwei Song, Luquan Ren, Lin Xu*, Siyao Yu*, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Efficient Separation of SO2/NO2 on in-Situ Synthesized NaA Zeolite Membrane",
              href: "https://doi.org/10.1016/j.memsci.2024.123097",
              desc: "Journal of Membrane Science，2024, 709: 123097；影响因子：9；中科院1区 / JCR Q1；通讯情况：三通讯；作者：Ziyi Li, Xinjian Liu, Yongyan Deng, Xiong Yang*, Yixing Guan, Jiaxing Wu, Junchao Dong, Zhiyong Chang*, Xiaoqin Zou*",
              tags: ["Journal of Membrane Science", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Fine-tuning porosity of In-MOFs with ncb topology based on reticular chemistry for one-step purification C2H4 from ternary C2H6/C2H4/C2H2 mixtures",
              href: "https://doi.org/10.1016/j.seppur.2024.127863",
              desc: "Separation and Purification Technology，2024, 349: 127863；影响因子：9；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Wen Li, Borong Zhang, Zhaohui Shi, Lirong Zhang, Zhiyong Chang*, Yunling Liu*",
              tags: ["Separation and Purificatio...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Chinese architecture inspired smart roof tile integrating radiation cooling, water harvesting, and energy recycling",
              href: "https://doi.org/10.1016/j.nanoen.2024.109709",
              desc: "Nano Energy，2024, 127: 109709；影响因子：17.1；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Heng Xie, Yu Du, Xiaolong Li, Congyuan Zhang, Weilong Zhou, Xiao Yang, Zhiyong Chang*, Ting Wu*, Jinping Qu",
              tags: ["Nano Energy", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Soil pesticides pollution detection and specific recognition using electronic nose",
              href: "https://doi.org/10.1016/j.snb.2024.135492",
              desc: "Sensors and Actuators B: Chemical，2024, 408: 135492；影响因子：8；中科院1区 / JCR Q1；通讯情况：通讯；作者：Cheng Kong, Lili Ren, Xiaohu Shi, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "An unprecedented Cu6 cluster-based bimetallic MOF with multiple open sites for high CO2 capture and efficient CO2 conversion",
              href: "https://doi.org/10.1039/d4qi00692e",
              desc: "Inorganic Chemistry Frontiers，2024, 11: 3494-3502；影响因子：7；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Xueyue Yu, Jiaming Gu, Baobing Tang, Tong Xu, Guanghua Li, Zhiyong Chang*, Yunling Liu*",
              tags: ["Inorganic Chemistry Fronti...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Optical-domain modulation cancellation method for background-suppression and dual-gas detection in light-induced thermo-elastic spectroscopy",
              href: "https://doi.org/10.1016/j.snb.2023.135168",
              desc: "Sensors and Actuators B: Chemical，2024, 404: 135168；影响因子：8；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Yanming Ma, Xin Sui, Fang Song, Zhiyong Chang*, Yu Zhang, Chuantao Zheng*, Yiding Wang, Frank K. Tittel",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Simultaneous atmospheric CH4, CO2 and O2 detection using fiber-optic switch (FOS)-based time-division multiplexed NIR laser long optical path absorption spectroscopy",
              href: "https://doi.org/10.1016/j.snb.2023.135256",
              desc: "Sensors and Actuators B: Chemical，2024, 404: 135256；影响因子：8；中科院1区 / JCR Q1；通讯情况：通讯；作者：Jingmin Dang, Junhe Zhang, Tianhua Chen, Chuantao Zheng, Yujing Sun, Haiye Yu, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Development an electronic nose to recognize pesticides in groundwater",
              href: "https://doi.org/10.1016/j.talanta.2023.125506",
              desc: "Talanta，2024, 269: 125506；影响因子：6.1；中科院1区 / JCR Q1；通讯情况：通讯；作者：Bingyang Wang, Donghui Chen, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Talanta", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Slow-light-enhanced polarization division multiplexing infrared absorption spectroscopy for on-chip wideband multigas detection in a 1D photonic crystal waveguide",
              href: "https://doi.org/10.1021/acs.analchem.3c04793",
              desc: "Analytical Chemistry，2024, 96(8): 3445-3453；影响因子：6.7；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Zihang Peng, Yijun Huang, Kaiyuan Zheng, Yuting Min, Huan Zhao, Mingquan Pi, Fang Song, Chuantao Zheng*, Yu Zhang, Zhiyong Chang*, Yiding Wang",
              tags: ["Analytical Chemistry", "中科院1区", "JCR Q1"],
            },
            {
              year: "2024",
              title: "Rapid identification of pesticides in soil by bionic sniffing sensing system with unknown category detection function",
              href: "https://doi.org/10.1016/j.compag.2024.108667",
              desc: "Computers and Electronics in Agriculture，2024, 217: 108667；影响因子：8.3；中科院1区 / JCR Q1；通讯情况：通讯；作者：Cheng Kong, Lili Ren, Tao Zhang, Youhong Sun, Zhiyong Chang*",
              tags: ["Computers and Electronics ...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Bio-inspired spindle-shaped wrinkled Au/ZnO nanoparticles for H2S-sensing enhancement",
              href: "https://doi.org/10.1016/j.ceramint.2023.09.270",
              desc: "Ceramics International，2023, 49(24): 39917-39925；影响因子：5.2；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Mingwei Xu, Qingqing Zhou, Zitong Kan, Shengyan Yin, Yudong Song, Xinjian Shi, Lin Xu, Zhiyong Chang*, Hang Sun*",
              tags: ["Ceramics International", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Experimental study of the formation and decomposition of mixed gas hydrates in water-hydrocarbon system",
              href: "https://doi.org/10.1016/j.cej.2023.146263",
              desc: "Chemical Engineering Journal，2023, 475: 146263；影响因子：15.1；中科院1区 / JCR Q1；通讯情况：双通讯（李胜利第一也是通讯）；作者：Shengli Li*, Shijing Zhang, Kai Su, Qiang Liu, Haonan Wu, Zhiyong Chang*",
              tags: ["Chemical Engineering Journal", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Study on the kinetic-guided pyrolysis of oil shale kerogen catalyzed by needle-like NiFe-LDH",
              href: "https://doi.org/10.1016/j.fuproc.2023.107954",
              desc: "Fuel Processing Technology，2023, 252: 107954；影响因子：7.5；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Tianbao Liu, Fei Liu, Weiguang Shi*, Wei Li, Benxian Li, Xiangbin Liu, Xiaofei Fu, Sunhua Deng, Zhiyong Chang*",
              tags: ["Fuel Processing Technology", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Towards accuracy recognition and content estimation of typical pesticides in groundwater via electronic nose",
              href: "https://doi.org/10.1016/j.sna.2023.114642",
              desc: "Sensors and Actuators A: Physical，2023, 362: 114642；影响因子：4.6；中科院2区 / JCR Q1；通讯情况：通讯；作者：Donghui Chen, Bingyang Wang, Tao Zhang, Zhiyong Chang*",
              tags: ["Sensors and Actuators A: P...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Detection and classification of pesticide residues in dandelion (Taraxacum officinale L.) by electronic nose combined with chemometric approaches",
              href: "https://doi.org/10.25165/j.ijabe.20231605.7886",
              desc: "International Journal of Agricultural and Biological Engineering，2023, 16(5): 181-188；影响因子：2.4；中科院2区 / JCR Q2；通讯情况：三通讯；作者：Jianlei Qiao, Xinmei Jiang, Xiaohui Weng, Hongbo Cui, Chang Liu*, Yuanjun Zou, Hailing Yu, Yucai Feng*, Zhiyong Chang*",
              tags: ["International Journal of A...", "中科院2区", "JCR Q2"],
            },
            {
              year: "2023",
              title: "Development of electrospun filter with high efficiency to reduce disturbance on gas detection in dusty environments",
              href: "https://doi.org/10.1002/app.54113",
              desc: "Journal of Applied Polymer Science，2023, 140(31): e54113；影响因子：3；中科院3区 / JCR Q2；通讯情况：双通讯；作者：Bo Zhao, Li Guo*, Mingze Han, Yunhong Liang, Mo Li, Shuli Ma, Tianjian Tong, Zhiyong Chang*",
              tags: ["Journal of Applied Polymer...", "中科院3区", "JCR Q2"],
            },
            {
              year: "2023",
              title: "Exploring the effect of different secondary building units as lewis acid sites in MOF materials for the CO2 cycloaddition reaction",
              href: "https://doi.org/10.1021/acs.inorgchem.3c01146",
              desc: "Inorganic Chemistry，2023, 62(29): 11518-11527；影响因子：4.6；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Xueyue Yu, Jiaming Gu, Xinyao Liu, Zhiyong Chang*, Yunling Liu*",
              tags: ["Inorganic Chemistry", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Hierarchical electronic nose detection and assessment technology for the reusage of land contaminated with petroleum hydrocarbons",
              href: "https://doi.org/10.1016/j.snb.2023.133940",
              desc: "Sensors and Actuators B: Chemical，2023, 390: 133940；影响因子：8.4；中科院1区 / JCR Q1；通讯情况：通讯；作者：Xiangyu Luan#, Cheng Kong#, Zongwei Yao, Yang Sun, Zhiyong Chang*",
              tags: ["Sensors and Actuators B: C...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "Improving recognition accuracy of pesticides in groundwater by applying tradaboost transfer learning method",
              href: "https://doi.org/10.3390/s23083856",
              desc: "Sensors，2023, 23(8): 3856；影响因子：3.9；中科院2区 / JCR Q2；通讯情况：通讯；作者：Donghui Chen, Bingyang Wang, Xiao Yang, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Sensors", "中科院2区", "JCR Q2"],
            },
            {
              year: "2023",
              title: "Development of an electronic nose to characterize water quality parameters and odor concentration of wastewater emitted from different phases in a wastewater treatment plant",
              href: "https://doi.org/10.1016/j.watres.2023.119878",
              desc: "Water Research，2023, 235: 119878；影响因子：12.8；中科院1区 / JCR Q1；通讯情况：通讯；作者：Bingyang Wang#, Xiaodan Li#, Donghui Chen, Xiaohui Weng, Zhiyong Chang*",
              tags: ["Water Research", "中科院1区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "A two-step e-nose system for vehicle drunk driving rapid detection",
              href: "https://doi.org/10.3390/app13063478",
              desc: "Applied Sciences-Basel，2023, 13: 3478；影响因子：2.7；中科院3区 / JCR Q2；通讯情况：双通讯；作者：Fangrong Wang, Dongsheng Bai, Zhaoyang Liu, Zongwei Yao, Xiaohui Weng*, Conghao Xu, Kaidi Fan, Zihan Zhao, Zhiyong Chang*.",
              tags: ["Applied Sciences-Basel", "中科院3区", "JCR Q2"],
            },
            {
              year: "2023",
              title: "Recognition of oil content for oil shale by electronic nose based on transient and steady-state fusion feature extraction method",
              href: "https://doi.org/10.1109/jsen.2023.3236326",
              desc: "IEEE Sensors Journal，2023, 23(4): 3453-3461；影响因子：4.3；中科院2区 / JCR Q1；通讯情况：双通讯；作者：Lili Ren, Cheng Kong, Xiaohui Weng, Rongsheng Zhao, Zongwei Yao*, Zhiyong Chang*",
              tags: ["IEEE Sensors Journal", "中科院2区", "JCR Q1"],
            },
            {
              year: "2023",
              title: "A preliminary screening system for diabetes based on in-car electronic nose",
              href: "https://doi.org/10.1530/ec-22-0437",
              desc: "Endocrine Connections，2023, 12: e220437；影响因子：2.9；中科院3区 / JCR Q3；通讯情况：双通讯；作者：Xiaohui Weng, Gehong Li, Ziwei Liu, Rui Liu*, Zhaoyang Liu, Songyang Wang, Shishun Zhao, Xiaotong Ma, Zhiyong Chang*",
              tags: ["Endocrine Connections", "中科院3区", "JCR Q3"],
            },
            {
              year: "2023",
              title: "A bionic degassing device inspired by gills: application on underwater oil and gas detection",
              href: "https://doi.org/10.1007/s42235-022-00264-3",
              desc: "Journal of Bionic Engineering，2023, 20(1): 253-266；影响因子：4；中科院2区 / JCR Q1；通讯情况：通讯；作者：Yongming Yao, Hang Li, Youhong Sun, Zhiyong Chang*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2022",
              title: "Design and optimization of electronic nose sensor array for real-time and rapid detection of vehicle exhaust pollutants",
              href: "https://doi.org/10.3390/chemosensors10120496",
              desc: "Chemosensors，2022, 10, 496；影响因子：4.2；中科院3区 / JCR Q2；通讯情况：双通讯；作者：Jin Tong, Chengxin Song, Tianjian Tong, Xuanjie Zong, Zhaoyang Liu, Songyang Wang, Lidong Tan, Yinwu Li*, Zhiyong Chang*",
              tags: ["Chemosensors", "中科院3区", "JCR Q2"],
            },
            {
              year: "2022",
              title: "Model development for alcohol concentration in exhaled air at low temperature using electronic nose",
              href: "https://doi.org/10.3390/chemosensors10090375",
              desc: "Chemosensors，2022, 10, 375；影响因子：4.2；中科院3区 / JCR Q2；通讯情况：双通讯；作者：Lidong Tan, Jiexi Wang, Guiyou Liang*, Zongwei Yao, Xiaohui Weng, Fangrong Wang, Zhiyong Chang*",
              tags: ["Chemosensors", "中科院3区", "JCR Q2"],
            },
            {
              year: "2022",
              title: "Development trend of electronic nose technology in closed cabins gas detection: a review",
              href: "https://doi.org/10.3390/app12189326",
              desc: "Applied Sciences-Basel，2022, 12, 9326；影响因子：2.7；中科院3区 / JCR Q2；通讯情况：双通讯；作者：Lidong Tan, Zhaohui Feng, Hongli Zheng*, Zongwei Yao, Xiaohui Weng, Fangrong Wang, Zhiyong Chang*.",
              tags: ["Applied Sciences-Basel", "中科院3区", "JCR Q2"],
            },
            {
              year: "2022",
              title: "Diverse scenarios selective perception of H2S via cobalt sensitized MOF filter membrane coated Three-Dimensional metal oxide sensor",
              href: "https://doi.org/10.1016/j.cej.2022.138014",
              desc: "Chemical Engineering Journal，2022, 450, 138014；影响因子：15.1；中科院1区 / JCR Q1；通讯情况：三通讯；作者：Qingqing Zhou, Long Yang, Zitong Kan, Jiekai Lyu, Mingxuan Wang, Biao Dong, Xue Bai, Zhiyong Chang*, Hongwei Song*, Lin Xu*",
              tags: ["Chemical Engineering Journal", "中科院1区", "JCR Q1"],
            },
            {
              year: "2022",
              title: "Investigation and optimization of PDMS/PES membrane on morphology and performance for methane-water separation",
              href: "https://doi.org/10.1016/j.micromeso.2022.112078",
              desc: "Microporous and Mesoporous Materials，2022, 341, 112078；影响因子：5.2；中科院2区 / JCR Q1；通讯情况：双通讯；作者：Guolong Lu, Hao Cui, Xiaohui Weng, Youhong Sun*, Zhiyong Chang*",
              tags: ["Microporous and Mesoporous...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2022",
              title: "A two-stage framework for detection of pesticide residues in soil based on gas sensors",
              href: "https://doi.org/10.1016/j.cjac.2022.100124",
              desc: "Chinese Journal of Analytical Chemistry，2022, 50(11): 100124；影响因子：1.2；中科院3区 / JCR Q4；通讯情况：通讯；作者：Xiaohu Shi, Yuheng Qiao, Xiangyu Luan, Yuping Yuan, Lin Xu, Zhiyong Chang*",
              tags: ["Chinese Journal of Analyti...", "中科院3区", "JCR Q4"],
            },
            {
              year: "2022",
              title: "Inspired by tree frog: bionic design of tread pattern and its wet friction properties",
              href: "https://doi.org/10.1007/s42235-022-00184-2",
              desc: "Journal of Bionic Engineering，2022, 19: 1064-1076；影响因子：2.995；中科院2区 / JCR Q1；通讯情况：双通讯；作者：Donghui Chen, Xiao Yang, Menghua Zhong, Chong Chen, Lihui Wang, Jingchun Wang, Xiaohui Weng*, Yinwu Li, Zhiyong Chang*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2022",
              title: "Real-time monitoring of the oil shale pyrolysis process using a bionic electronic nose",
              href: "https://doi.org/10.1016/j.fuel.2021.122672",
              desc: "Fuel，2022, 313: 122672；影响因子：7.4；中科院1区 / JCR Q1；通讯情况：通讯；作者：Rongsheng Zhao, Cheng Kong, Luquan Ren, Youhong Sun, Zhiyong Chang",
              tags: ["Fuel", "中科院1区", "JCR Q1"],
            },
            {
              year: "2022",
              title: "A multi-platform sensor for selective and sensitive H2S monitoring: three-dimensional macroporous ZnO encapsulated by MOFs with small Pt nanoparticles",
              href: "https://doi.org/10.1016/j.jhazmat.2021.128075",
              desc: "Journal of Hazardous Materials，2022, 426: 128075；影响因子：13.6；中科院1区 / JCR Q1；通讯情况：双通讯；作者：Qingqing Zhou, Lin Xu*, Zitong Kan, Long Yang, Zhiyong Chang*, Biao Dong, Xue Bai, Geyu Lu, Hongwei Song",
              tags: ["Journal of Hazardous Mater...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2021",
              title: "Constrain on oil recovery stage during oil shale subcritical water extraction process based on carbon isotope fractionation character",
              href: "https://doi.org/10.3390/en14237839",
              desc: "Energies，2021, 14(23), 7839;；影响因子：3.252；中科院3区 / JCR Q3；通讯情况：双通讯；作者：Rongsheng Zhao,Luquan Ren,Sunhua Deng,Youhong Sun*, Zhiyong Chang*",
              tags: ["Energies", "中科院3区", "JCR Q3"],
            },
            {
              year: "2021",
              title: "Bionic layout optimization of sensor array in electronic nose for oil shale pyrolysis process detection",
              href: "https://doi.org/10.1007/s42235-021-0022-2",
              desc: "Journal of Bionic Engineering，2021, 18(2): 441-452；影响因子：2.995；中科院2区 / JCR Q1；通讯情况：通讯；作者：Xiaohui Weng, Youhong Sun, Jun Xie, Sunhua Deng, Zhiyong Chang*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2021",
              title: "Detection of volatile organic compounds (VOCs) in livestock houses based on electronic nose",
              href: "https://doi.org/10.3390/app11052337",
              desc: "Applied Sciences，2021, 11(5): 2337；影响因子：2.838；中科院3区 / JCR Q2；通讯情况：通讯；作者：Xiaohui Weng, Cheng Kong, Hongyang Jin, Dongxue Chen, Chunguang Li*, Yinwu Li, Lili Ren, Yingkui Xiao, Zhiyong Chang*",
              tags: ["Applied Sciences", "中科院3区", "JCR Q2"],
            },
            {
              year: "2021",
              title: "Near-infrared off-axis integrated cavity output spectroscopic gas sensor for real-time, in situ atmospheric methane monitoring",
              href: "https://doi.org/10.1109/jsen.2020.3042697",
              desc: "IEEE Sensors Journal，2021, 21(5): 6830-6838；影响因子：3.301；中科院2区 / JCR Q1；通讯情况：通讯；作者：Kaiyuan Zheng, Chuantao Zheng*, Haipeng Zhang, Junhao Li, Zidi Liu, Zhiyong Chang*, Yu Zhang, Yiding Wang, Frank K. Tittel",
              tags: ["IEEE Sensors Journal", "中科院2区", "JCR Q1"],
            },
            {
              year: "2020",
              title: "Traditional sensory evaluation and bionic electronic nose as innovative tools for the packaging performance evaluation of chitosan film",
              href: "https://doi.org/10.3390/polym12102310",
              desc: "Polymers，2020, 12(10): 2310.；影响因子：4.329；中科院2区 / JCR Q1；通讯情况：通讯；作者：Wei Song, Jian Xu, Lili Ren*, Li Guo, Jin Tong, Liyan Wang, Zhiyong Chang*",
              tags: ["Polymers", "中科院2区", "JCR Q1"],
            },
            {
              year: "2020",
              title: "A comprehensive method for assessing meat freshness using fusing electronic nose, computer vision and artificial tactile technologies",
              href: "https://doi.org/10.1155/2020/8838535",
              desc: "Journal of Sensors，2020: 8838535；影响因子：2.137；中科院4区 / JCR Q3；通讯情况：通讯；作者：Xiaohui Weng, Xiangyu Luan, Cheng Kong, Zhiyong Chang*, Yinwu Li, Shujun Zhang*, Salah Al-Majeed, Yingkui Xiao",
              tags: ["Journal of Sensors", "中科院4区", "JCR Q3"],
            },
            {
              year: "2020",
              title: "Bionic Design to Reduce Jacking Force for Trenchless Installations in Clay Soil",
              href: "https://doi.org/10.1007/s42235-020-0066-8",
              desc: "Journal of Bionic Engineering，卷: ‏ 17   期: ‏ 4   页: ‏ 686-694；影响因子：2.682；中科院2区 / JCR Q1；通讯情况：通讯；作者：Donghui Chen, Xiao Yang, Taidong Dai, Youhong Sun, Zhiyong Chang*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2020",
              title: "Bio-inspired design and evaluation of porous fences for mitigating fugitive dust",
              href: "https://doi.org/10.1007/s42235-020-0030-7",
              desc: "Journal of Bionic Engineering，2020, 17(2): 370-379；影响因子：2.682；中科院2区 / JCR Q1；通讯情况：通讯；作者：Li Guo, Dongsen Zhao, Bo Zhao, Jin Li, Jin Tong, Yunhai Ma, Zhiyong Chang*.",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2020",
              title: "Bio-inspired hierarchical assembly of Au/ZnO decorated carbonized spinach leaves with enhanced photocatalysis performance",
              href: "https://doi.org/10.1016/j.jallcom.2020.154393",
              desc: "Journal of Alloys and Compounds，Volume 829, 15 July 2020, 论文编号 154393；影响因子：5.316；中科院1区 / JCR Q1；通讯情况：双通讯；作者：ZhenQin, Hang Sun*, Yanan Tang, Zhiyong Chang*, Shengyan Yin, Zhenning Liu",
              tags: ["Journal of Alloys and Comp...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2020",
              title: "Sensitive chemical sensor array based on nanozymes for discrimination of metal ions and teas",
              href: "https://doi.org/10.1002/bio.3730",
              desc: "Luminescence，Volume 35, Issue 2, 1 March 2020, Pages 321-327；影响因子：2.464；中科院4区 / JCR Q3；通讯情况：通讯；作者：Jiao Li, Qi Cheng, Hui Huang*, Meini Li, Shujun Yan, Yongxin Li*, Zhiyong Chang*",
              tags: ["Luminescence", "中科院4区", "JCR Q3"],
            },
            {
              year: "2020",
              title: "Hyperspectral Band Selection for Lithologic Discrimination and Geological Mapping",
              href: "https://doi.org/10.1109/jstars.2020.2964000",
              desc: "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing，Volume 13, 2020, 论文编号 8966510, Pages 471-486；影响因子：3.784；中科院2区 / JCR Q1；通讯情况：通讯；作者：Yulei Tan, Laijun Lu, Lorenzo Bruzzone, Renchu Guan, Zhiyong Chang*, Chen Yang*.",
              tags: ["IEEE Journal of Selected T...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2019",
              title: "Hydrophobic nanostructures fabricated by ferric nitrate etching method on single crystalline silicon surface",
              href: "https://doi.org/10.1016/j.colsurfa.2019.123999",
              desc: "Colloids and Surfaces A: Physicochemical and Engineering Aspects，卷: 583 文献号: 123999 出版年: DEC 20 2019；影响因子：3.99；中科院2区 / JCR Q2；通讯情况：一作；作者：Zhiyong Chang,Youhong Sun*,Jian Xu,Xuanjie Zong,Qiongqiong Tang,Li Guo,Lili Ren*,Wen-Hsing Cheng",
              tags: ["Colloids and Surfaces A: P...", "中科院2区", "JCR Q2"],
            },
            {
              year: "2019",
              title: "Preparation and characterization of porous chitosan microspheres and adsorption performance for hexavalent chromium",
              href: "https://doi.org/10.1016/j.ijbiomac.2019.06.007",
              desc: "International Journal of Biological Macromolecules，Volume 135, 15 August 2019, Pages 898-906；影响因子：5.162；中科院1区 / JCR Q1；通讯情况：通信；作者：Lili Ren, Jian Xu, Yuchen Zhang, Jiang Zhou, Donghui Chen, Zhiyong Chang*",
              tags: ["International Journal of B...", "中科院1区", "JCR Q1"],
            },
            {
              year: "2019",
              title: "Experimental investigation of vegetative environment buffers in reducing particulate matters emitted from ventilated poultry house",
              href: "https://doi.org/10.1080/10962247.2019.1598518",
              desc: "Journal of the Air and Waste Management Association，Volume 69, Issue 8, 3 August 2019, Pages 934-943；影响因子：2.245；中科院4区 / JCR Q3；通讯情况：通信；作者：Guo Li, Ma Shuli, Zhao Dongsen,Zhao, Bo; Xu, Bingfang; Wu, Jiwen; Tong, Jin; Chen Donghui, Ma Yunhai, Li Mo; Chang Zhiyong*",
              tags: ["Journal of the Air and Was...", "中科院4区", "JCR Q3"],
            },
            {
              year: "2019",
              title: "FEM analysis in excellent cushion characteristic of ostrich (Struthio camelus) toe pads",
              href: "https://doi.org/10.1371/journal.pone.0216141",
              desc: "PLoS ONE，Volume 14, Issue 5, May 2019；影响因子：2.74；中科院3区 / JCR Q2；通讯情况：通信；作者：Rui Zhang*  , Lei Ling , Dianlei Han , Haitao Wang , Guolong Yu , Lei Jiang , Dong Li , Zhiyong Chang*",
              tags: ["PLoS ONE", "中科院3区", "JCR Q2"],
            },
            {
              year: "2019",
              title: "Weighted Summation: Feature Extraction of Farm Pigsty Data for Electronic Nose",
              href: "https://doi.org/10.1109/access.2019.2929526",
              desc: "IEEE Access，Volume 7, 2019, 论文编号 8765732, Pages 96732-96742；影响因子：3.745；中科院3区 / JCR Q2；通讯情况：通信；作者：CHENG KONG, SHISHUN ZHAO, XIAOHUI WENG, CHANG LIU, RENCHU GUAN, AND ZHIYONG CHANG*",
              tags: ["IEEE Access", "中科院3区", "JCR Q2"],
            },
            {
              year: "2018",
              title: "An Optimal Wet Friction Plate Inspired by Biological Surface Patterns",
              href: "https://doi.org/10.1007/s42235-018-0074-0",
              desc: "Journal of Bionic Engineering，Volume 15, Issue 5, 1 September 2018, Pages 872-882；影响因子：2.463；中科院2区 / JCR Q1；通讯情况：通信；作者：Donghui Chen; Yuchen Zhang; Gang Long; Wei Liu; Xiuhui Li; Youhong Sun; Zhiyong Chang*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2018",
              title: "Bionic Optimization Design of Electronic Nose Chamber for Oil and Gas Detection",
              href: "https://doi.org/10.1007/s42235-018-0044-6",
              desc: "Journal of Bionic Engineering，Volume 15, Issue 3, 1 May 2018, Pages 533-544；影响因子：2.463；中科院2区 / JCR Q1；通讯情况：一作；作者：Zhiyong Chang,Youhong Sun*,Yuchen Zhang,Yanli Gao, Xiaohui Weng,Donghui Chen, Liewe David, Jun Xie",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2018",
              title: "Bionic Design of the Bumper Beam Inspired by the Bending and Energy Absorption Characteristics of Bamboo",
              href: "https://doi.org/10.1155/2018/8062321",
              desc: "Applied Bionics and Biomechanics，Volume 2018, 2018, 论文编号 8062321；影响因子：1.525；中科院4区 / JCR Q4；通讯情况：通信；作者：Meng Zou, Jiafeng Song, Shucai Xu, Shengfu Liu, and Zhiyong Chang*",
              tags: ["Applied Bionics and Biomec...", "中科院4区", "JCR Q4"],
            },
            {
              year: "2017",
              title: "Stability Performance of Inflatable Tube Imitating Clanis Bilineata Larva under Axial Pressure",
              href: "https://doi.org/10.1142/s0219519417400280",
              desc: "Journal of Mechanics in Medicine and Biology，Volume 17, Issue 7, 1 November 2017, 论文编号 1740028；影响因子：0.875；中科院4区 / JCR Q4；通讯情况：通信；作者：DONGHUI CHEN, JIANHUA LV, WEI LIU, ZHIYONG CHANG* and XIAO YANG",
              tags: ["Journal of Mechanics in Me...", "中科院4区", "JCR Q4"],
            },
            {
              year: "2017",
              title: "Bacterial Infection Potato Tuber Soft Rot Disease Detection Based on Electronic Nose",
              href: "https://doi.org/10.1515/biol-2017-0044",
              desc: "Open Life Sciences，Volume 12, Issue 1, 1 January 2017, Pages 379-385；影响因子：0.764；中科院4区 / JCR Q4；通讯情况：一作；作者：Zhiyong Chang, Jianhua Lv, Hongyan Qi, Yunhai Ma\n, Donghui Chen, Jun Xie* and Youhong Sun*",
              tags: ["Open Life Sciences", "中科院4区", "JCR Q4"],
            },
            {
              year: "2016",
              title: "Design and Experiments of Biomimetic Stubble Cutter",
              href: "https://doi.org/10.1016/s1672-6529(16)60306-2",
              desc: "Journal of Bionic Engineering，Volume 13, Issue 2, 1 April 2016, Pages 335-343；影响因子：2.388；中科院2区 / JCR Q1；通讯情况：一作；作者：Zhiyong Chang, Wei Liu, Jin Tong, Li Guo, Heng Xie, Xiao Yang Haifeng Mu, Donghui Chen*",
              tags: ["Journal of Bionic Engineer...", "中科院2区", "JCR Q1"],
            },
            {
              year: "2016",
              title: "Application of a bionic ring structure on drill pipe surfaces to improve the performance of anti-corrosion coatings",
              href: "https://doi.org/10.1108/acmm-11-2015-1607",
              desc: "Anti-Corrosion Methods and Materials，Volume 63, Issue 3, 2016, Pages 177-183；影响因子：0.364；中科院4区 / JCR Q4；通讯情况：通信；作者：Ma, Yunhai; Wang, Hubiao; Zhang, Xin ; Shang, Wenbo ; Tong, Jin ; Chang, Zhiyong*",
              tags: ["Anti-Corrosion Methods and...", "中科院4区", "JCR Q4"],
            },
          ],
        },
        {
          title: "授权专利",
          type: "专利",
          records: [
            {
              year: "2025",
              title: "一种随钻原位南极冰层痕量气体富集的监测装置和方法",
              href: "https://patents.google.com/patent/CN119309872B/zh",
              desc: "授权日期：2025.11.04；专利号：ZL202411457168.5；公告号：CN119309872B；发明人：常志勇, 陈子豪, 孙友宏, 靳宏杨, 杨逍, 党敬民, 李冰, 范晓鹏, 张楠, 翁小辉, 孔铖, 栾祥宇",
              tags: ["授权专利", "CN119309872B"],
            },
            {
              year: "2025",
              title: "一种随钻原位土壤有机污染检测装置和检测方法",
              href: "https://patents.google.com/patent/CN116242989B/zh",
              desc: "授权日期：2025.09.19；专利号：ZL202310232183.9；公告号：CN116242989B；发明人：常志勇, 孙友宏, 靳宏杨, 孔铖, 姚宗伟, 翁小辉, 徐琳, 邓孙华, 李胜利",
              tags: ["授权专利", "CN116242989B"],
            },
            {
              year: "2024",
              title: "一种水下防污电子鼻腔室",
              href: "https://patents.google.com/patent/CN110967460B/zh",
              desc: "授权日期：2024.07.23；专利号：ZL201911124262.8；公告号：CN110967460B；发明人：常志勇, 闫毅帆, 寇淑清, 翁小辉, 任丽丽, 黄卉, 梁平, 李因武, 李家亿",
              tags: ["授权专利", "CN110967460B"],
            },
            {
              year: "2024",
              title: "一种基于多气敏传感系统的油矿品质原位快速检测装置",
              href: "https://patents.google.com/patent/CN116087426B/zh",
              desc: "授权日期：2024.06.04；专利号：ZL202310082228.9；公告号：CN116087426B；发明人：常志勇, 靳宏杨, 孙友宏, 徐丛浩, 姚宗伟, 刘宝昌, 郭威, 高科, 郭丽, 翁小辉, 李默",
              tags: ["授权专利", "CN116087426B"],
            },
            {
              year: "2024",
              title: "一种油田采出水水质重金属检测装置",
              href: "https://patents.google.com/patent/CN108061787B/zh",
              desc: "授权日期：2024.01.30；专利号：ZL201810052007.6；公告号：CN108061787B；发明人：常志勇, 孙友宏, 张宇晨, 刘宝昌, 邓孙华, 高科, 贾瑞, 翁小辉, 任丽丽, 谢军, 陈东辉, 马云海",
              tags: ["授权专利", "CN108061787B"],
            },
            {
              year: "2024",
              title: "用于油田采出水重金属检测的仿生吸附采样部件",
              href: "https://patents.google.com/patent/CN108132167B/zh",
              desc: "授权日期：2024.01.16；专利号：ZL201810052008.0；公告号：CN108132167B；发明人：常志勇, 孙友宏, 张宇晨, 郭威, 邓孙华, 高科, 贾瑞, 翁小辉, 任丽丽, 谢军, 陈东辉, 马云海",
              tags: ["授权专利", "CN108132167B"],
            },
            {
              year: "2024",
              title: "仿生鱼嗅囊结构的录井脱气器",
              href: "https://patents.google.com/patent/CN106703726B/zh",
              desc: "授权日期：2024.01.09；专利号：ZL201710013739.X；公告号：CN106703726B；发明人：常志勇, 孙友宏, 李金光, 佟金, 高科, 刘宝昌, 郭威, 贾瑞, 邓孙华, 陈东辉, 马云海",
              tags: ["授权专利", "CN106703726B"],
            },
            {
              year: "2023",
              title: "一种仿猪鼻腔鼻甲骨及鲨鱼表皮结构的仿生电子鼻腔室",
              href: "https://patents.google.com/patent/CN106950254B/zh",
              desc: "授权日期：2023.11.10；专利号：ZL201710315936.7；公告号：CN106950254B；发明人：常志勇, 佟金, 蒋啸虎, 李金光, 陈东辉, 马云海, 孙霁宇",
              tags: ["授权专利", "CN106950254B"],
            },
            {
              year: "2023",
              title: "一种具有仿生导流结构与可变位传感器的气体探测器",
              href: "https://patents.google.com/patent/CN108333315B/zh",
              desc: "授权日期：2023.10.17；专利号：ZL201810314013.4；公告号：CN108333315B；发明人：常志勇, 华晓松, 张宇晨, 李秀慧, 翁小辉, 杨润, 吕建华, 谢军, 任丽丽, 郭丽, 李俊宏, 陈东辉, 卢国龙, 刘伟",
              tags: ["授权专利", "CN108333315B"],
            },
            {
              year: "2023",
              title: "一种集成仿生一体式半透膜脱气器",
              href: "https://patents.google.com/patent/CN106401582B/zh",
              desc: "授权日期：2023.05.26；专利号：ZL201611074677.5；公告号：CN106401582B；发明人：常志勇, 孙友宏, 吕建华, 翁小辉, 高科, 刘宝昌, 郭威, 贾瑞, 邓孙华, 陈东辉, 马云海",
              tags: ["授权专利", "CN106401582B"],
            },
            {
              year: "2023",
              title: "一种仿新月形沙丘的气体富集装置",
              href: "https://patents.google.com/patent/CN109283040B/zh",
              desc: "授权日期：2023.04.25；专利号：ZL201811363120.2；公告号：CN109283040B；发明人：常志勇, 龙刚, 张宇晨, 陈东辉, 翁小辉, 郭丽, 黄汇, 任丽丽, 卢国龙, 马云海, 孙霁宇, 王海燕",
              tags: ["授权专利", "CN109283040B"],
            },
            {
              year: "2022",
              title: "一种利用电子鼻对油页岩裂解过程中成熟度的识别方法",
              href: "https://patents.google.com/patent/CN113671116B/zh",
              desc: "授权日期：2022.05.27；专利号：ZL202110811545.0；公告号：CN113671116B；发明人：常志勇, 栾祥宇, 孔铖, 靳宏杨, 赵容生, 任丽丽, 翁小辉, 郭威, 孙友宏",
              tags: ["授权专利", "CN113671116B"],
            },
            {
              year: "2018",
              title: "一种仿生烃类气体吸附部件",
              href: "https://patents.google.com/patent/CN106215622B/zh",
              desc: "授权日期：2018.10.02；专利号：ZL201610883737.1；公告号：CN106215622B；发明人：常志勇, 孙友宏, 田大越, 郭威, 刘宝昌, 高科, 陈东辉, 马云海",
              tags: ["授权专利", "CN106215622B"],
            },
            {
              year: "2018",
              title: "仿生井下烃类气体随钻检测装置",
              href: "https://patents.google.com/patent/CN105545300B/zh",
              desc: "授权日期：2018.10.02；专利号：ZL201510906090.5；公告号：CN105545300B；发明人：常志勇, 孙友宏, 雷程, 郭威, 刘宝昌, 高科, 贾瑞, 马云海",
              tags: ["授权专利", "CN105545300B"],
            },
            {
              year: "2018",
              title: "一种仿生气体吸附采样装置",
              href: "https://patents.google.com/patent/CN106168547A/zh",
              desc: "授权日期：2018.07.20；专利号：ZL201610871581.5；公告号：CN106168547A；发明人：常志勇, 刘伟, 吕建华, 陈东辉, 田大越, 佟金, 马云海, 孙霁宇",
              tags: ["授权专利", "CN106168547A"],
            },
            {
              year: "2018",
              title: "一种录井用仿生减污油气分离装置",
              href: "https://patents.google.com/patent/CN106474774B/zh",
              desc: "授权日期：2018.07.17；专利号：ZL201611074676.0；公告号：CN106474774B；发明人：常志勇, 孙友宏, 吕建华, 翁小辉, 刘宝昌, 高科, 邓孙华, 贾瑞, 郭威, 陈东辉, 马云海",
              tags: ["授权专利", "CN106474774B"],
            },
            {
              year: "2018",
              title: "一种基于电子鼻的井下油气检测方法",
              href: "https://patents.google.com/patent/CN104730122B/zh",
              desc: "授权日期：2018.03.09；专利号：ZL201510080504.3；公告号：CN104730122B；发明人：常志勇, 孙友宏, 杨逍, 郭威, 刘宝昌, 高科, 佟金, 邓孙华, 马云海, 陈东辉",
              tags: ["授权专利", "CN104730122B"],
            },
            {
              year: "2018",
              title: "一种仿生钻井液电子舌间歇采样装置",
              href: "https://patents.google.com/patent/CN105699130B/zh",
              desc: "授权日期：2018.02.06；专利号：ZL201610068673.X；公告号：CN105699130B；发明人：常志勇, 孙友宏, 刘伟, 陈东辉, 郭威, 刘宝昌, 高科, 马云海",
              tags: ["授权专利", "CN105699130B"],
            },
            {
              year: "2017",
              title: "基于豆天蛾幼虫身体结构的减振装置",
              href: "https://patents.google.com/patent/CN105179583B/zh",
              desc: "授权日期：2017.04.26；专利号：ZL201510631082.4；公告号：CN105179583B；发明人：常志勇, 孙友宏, 刘伟, 陈东辉, 刘宝昌, 郭威, 高科, 贾瑞",
              tags: ["授权专利", "CN105179583B"],
            },
            {
              year: "2017",
              title: "一种气源搜索定位装置",
              href: "https://patents.google.com/patent/CN105067766B/zh",
              desc: "授权日期：2017.01.25；专利号：ZL201510454032.3；公告号：CN105067766B；发明人：常志勇, 齐红岩, 田大越, 佟金, 马云海, 陈东辉, 慕海锋, 翁小辉",
              tags: ["授权专利", "CN105067766B"],
            },
            {
              year: "2017",
              title: "一种仿鼢鼠鼻腔电子鼻",
              href: "https://patents.google.com/patent/CN104360023B/zh",
              desc: "授权日期：2017.01.25；专利号：ZL201410651912.5；公告号：CN104360023B；发明人：常志勇, 慕海锋, 陈东辉, 佟金, 马云海, 孙霁宇, 郭丽丽, 李默, 周江",
              tags: ["授权专利", "CN104360023B"],
            },
            {
              year: "2016",
              title: "一种用于气体传感器表面的仿生微结构",
              href: "https://patents.google.com/patent/CN104931654B/zh",
              desc: "授权日期：2016.09.14；专利号：ZL201510320368.0；公告号：CN104931654B；发明人：常志勇, 杨逍, 慕海锋, 佟金, 陈东辉, 张东光, 马云海, 孙霁宇, 周江",
              tags: ["授权专利", "CN104931654B"],
            },
            {
              year: "2016",
              title: "一种仿鱼鼻腔的水合物随钻气测电子鼻",
              href: "https://patents.google.com/patent/CN104698131B/zh",
              desc: "授权日期：2016.07.06；专利号：ZL201510077937.3；公告号：CN104698131B；发明人：常志勇, 孙友宏, 杨逍, 郭威, 刘宝昌, 高科, 佟金, 邓孙华, 陈东辉, 马云海",
              tags: ["授权专利", "CN104698131B"],
            },
            {
              year: "2021",
              title: "Gas Logging System",
              href: "https://patents.google.com/patent/US11054407B2/en",
              desc: "授权日期：2021.07.06；专利号：US11054407B2；发明人：Yonghong Sun, Zhiyong Chang, Xiaohui Weng, Lili Ren, Baochang Liu, Renchu Guan, Wei Guo, Jun Xie, Ke Gao, Jianhua Lv, Wei Liu, Deng Sunhua.孙友宏, 常志勇, 翁小辉, 任丽丽, 刘宝昌, 管仁初, 郭威, 谢军, 高科, 吕建华,  刘伟, 邓孙华",
              tags: ["授权专利", "Google Patents"],
            },
            {
              year: "2026",
              title: "Photoelectric fusion in-situ detection device and method for thermal volatile gases and thermal evolution stages of underground oil shale",
              href: "https://patents.google.com/patent/US12618999B2/en",
              desc: "授权日期：2026.05.05；专利号：US 12618999B2；发明人：Zhiyong Chang, Cheng Kong, Chengxin Song, Xiangyu Luan, Xiaohui Weng, Zongwei Yao, Tao Zhang, Ruochen An, Deng Sunhua. 常志勇, 孔铖, 宋成鑫, 栾祥宇, 翁小辉, 姚宗伟, 张涛, 安若宸, 邓孙华",
              tags: ["授权专利", "Google Patents"],
            },
          ],
        },
        {
          title: "科研项目",
          type: "项目",
          records: [
            {
              year: "2024-2027",
              title: "深地国家科技重大专项“特深井底钻压精准控制”专题",
              href: "#project-2024-1",
              desc: "近三年代表性科研项目，经费 341 万元，常志勇教授为负责人。",
              tags: ["项目", "深地钻探"],
            },
            {
              year: "2023-2027",
              title: "国家重点研发计划“深海和极地关键技术与装备”专项课题",
              href: "#project-2023-1",
              desc: "近三年代表性科研项目，经费 875 万元，常志勇教授为负责人。",
              tags: ["项目", "深海极地"],
            },
            {
              year: "2023-2026",
              title: "国家自然科学基金联合重点项目",
              href: "#project-2023-2",
              desc: "近三年代表性科研项目，经费 306 万元，常志勇教授为负责人。",
              tags: ["项目", "自然科学基金"],
            },
          ],
        },
        {
          title: "获奖与转化",
          type: "成果",
          records: [
            {
              year: "2024",
              title: "中国商业联合会技术发明奖一等奖",
              href: "https://me.seu.edu.cn/czy/list.htm",
              desc: "常志勇教授获中国商业联合会技术发明奖一等奖，排名第 1。",
              tags: ["奖励", "一等奖"],
            },
            {
              year: "2023",
              title: "吉林省科学技术进步奖一等奖",
              href: "https://kjt.jl.gov.cn/xwzx/kjcg/202404/t20240410_8892470.html",
              desc: "常志勇教授获吉林省科学技术进步奖一等奖，排名第 1。",
              tags: ["奖励", "一等奖"],
            },
            {
              year: "应用",
              title: "相关技术在中国石油吉林油田、中国一汽等单位转化应用",
              href: "https://me.seu.edu.cn/czy/list.htm",
              desc: "相关技术服务东北振兴，并在中国石油吉林油田、中国一汽等单位转化应用。",
              tags: ["成果转化", "工程应用"],
            },
            {
              year: "2026",
              title: "新华网报道我国第42次南极科考新突破",
              href: "https://www.xinhuanet.com/government/20260409/b0e7ac4983ef4c7abbd574dd809d9fdb/c.html",
              desc: "报道聚焦秦岭站业务化运行、冰盖热水钻探、国产极地装备应用、南大洋生态调查和航空保障等突破，呼应团队极地探测与复杂条件采样研究方向。",
              tags: ["媒体报道", "新华社"],
            },
            {
              year: "2025",
              title: "人民日报报道长春推动科技成果向现实生产力转化",
              href: "assets/人民日报报道.png",
              desc: "《人民日报》2025年8月9日第01版报道提及常志勇教授在长春试车场地测试脑机接口设备，系统延时小于 0.2 秒。",
              tags: ["媒体报道", "人民日报"],
            },
            {
              year: "2025",
              title: "光电行业门户报道光驱动下的智能净水机器人",
              href: "https://b2b.csoe.org.cn/news/show-807.html",
              desc: "报道介绍吉林大学张永来教授团队联合常志勇教授团队在 PhotoniX 发表光驱动光催化蒸发器研究，构建无需电池、路径可控的智能净水机器人。",
              tags: ["媒体报道", "PhotoniX"],
            },
            {
              year: "2024",
              title: "吉林省科技厅报道气体仿生传感与随钻融合监控技术",
              href: "https://kjt.jl.gov.cn/xwzx/kjcg/202404/t20240410_8892470.html",
              desc: "报道介绍团队建立气体仿生特异传感与随钻多相融合监控关键技术体系，该技术荣获 2023 年度吉林省科技进步奖一等奖。",
              tags: ["媒体报道", "科技成果"],
            },
            {
              year: "2024",
              title: "人民网报道“地壳一号”向地球深部进军",
              href: "http://jl.people.com.cn/n2/2024/0730/c349771-40928696.html",
              desc: "报道聚焦吉林大学自主研发的“地壳一号”万米钻机及深部科学钻探，呈现地球深部探测与能源探测方向的吉林科技成果。",
              tags: ["媒体报道", "深部探测"],
            },
          ],
        },
      ],
    },

    life: {
      title: "学习生活",
      kicker: "Life",
      summary:
        "组会、实验、团建、学术交流和毕业合影共同呈现团队科研氛围与日常温度。",
      coverImage: "assets/page-covers/page-life.jpg",
      photos: [
        { title: "组会交流", image: "assets/life-1.png", href: "#life-1", desc: "每周讨论研究进展，及时梳理问题和下一步计划。" },
        { title: "实验现场", image: "assets/life-2.png", href: "#life-2", desc: "结合真实实验平台开展样机测试和数据分析。" },
        { title: "学术交流", image: "assets/life-3.png", href: "#life-3", desc: "参与会议、报告和合作交流，拓展研究视野。" },
        { title: "团队活动", image: "assets/life-4.png", href: "#life-4", desc: "记录团队生活和成长瞬间。" },
      ],
    },

    recruit: {
      title: "招生招聘",
      kicker: "Join Us",
      summary:
        "课题组每年招收 3-5 名硕博士研究生，欢迎本科生依托课题组开展深海、极地特种传感与机器人相关项目研究，并长期招聘博士后。",
      coverImage: "assets/page-covers/page-recruit.jpg",
      fit: [
        {
          title: "适合加入的同学",
          text: "对传感器、机器人、智能装备、控制算法、人工智能或油气/海洋工程有兴趣，愿意做实验、写代码、搭系统、跑现场。",
        },
        {
          title: "进组后能做什么",
          text: "从文献调研、实验平台搭建、数据采集与算法训练开始，逐步参与论文、专利、项目汇报和样机验证。",
        },
        {
          title: "我们期待什么",
          text: "不要求一开始什么都会，但希望你有好奇心、动手能力、长期投入的耐心，以及把问题做深做实的愿望。",
        },
      ],
      training: [
        "本科生：参与开放课题、实验训练、数据分析和样机测试，提前接触研究生阶段课题。",
        "硕士生：围绕一个明确工程问题完成系统设计、实验验证、论文发表或专利申请。",
        "博士生：面向国家重大需求开展关键机理、核心器件、系统装备和工程应用研究。",
        "博士后：结合个人基础承担项目攻关、平台建设、团队协同和成果转化任务。",
      ],
      directions: [
        "深海深地仿生传感与随钻气测仪器",
        "水下特种机器人与仿生导航控制",
        "复杂环境气体采样、富集与低浓度检测",
        "电子鼻、红外激光传感与智能识别算法",
        "脑机接口、人机增强与智能装备控制",
      ],
      positions: [
        {
          title: "硕士研究生",
          href: "#master",
          desc: "欢迎对深海油气仿生传感、随钻气测仪器、智能探测装备和机器人系统感兴趣的同学报考。",
          tags: ["硕士", "深海深地", "智能装备"],
        },
        {
          title: "博士研究生",
          href: "#phd",
          desc: "适合具备机械、电子、自动化、仪器、控制、人工智能、海洋工程、石油工程等背景的同学。",
          tags: ["博士", "交叉背景", "项目攻关"],
        },
        {
          title: "博士后 / 科研助理",
          href: "#postdoc",
          desc: "聚焦国家重大战略需求，欢迎有科研理想、创新探索能力和工程攻关兴趣的博士加入。",
          tags: ["博士后", "长期招聘", "工程转化"],
        },
      ],
      contact:
        "请将个人简历、研究兴趣和代表性成果发送至 zhiyongchang@seu.edu.cn，邮件标题建议为“姓名-申请方向-学历阶段”。",
    },
  },

  footer: {
    address: "江苏省南京市 东南大学",
    email: "zhiyongchang@seu.edu.cn",
  },
};
